sonar.projectKey=AURA
sonar.projectName=AURA
sonar.sources=backend

sonar.exclusions=backend/venv/**, backend/.venv/**, **/__pycache__/**, **/*.dll, **/*.pyd, **/*.bin, **/*.pt, **/*.onnx, **/logs/**, **/uploads/**, **/data/**

sonar.python.version=3.11
sonar.scm.disabled=true
sonar.host.url=http://host.docker.internal:9000