sonar.projectKey=AURA
sonar.projectName=AURA
sonar.sources=.

# অনাবশ্যক ভারী ফোল্ডার ও বাইনারি ফাইল বাদ দিন
sonar.exclusions=venv/**, .venv/**, **/__pycache__/**, **/*.dll, **/*.pyd, **/*.bin, **/*.pt, **/*.onnx, **/logs/**, **/uploads/**, **/data/**

sonar.python.version=3.11
sonar.scm.disabled=true
sonar.host.url=http://localhost:9000
sonar.token=sqp_1f4f7f7a155619e10a42efa68bf4a7f70aa3dfd1